### ISSUE TITLE
XMLHttpRequest cannot load https://www.reddit.com/api/v1/access_token

### ISSUE THREAD

**Issue by derrick56007** [stevenroose/dart-reddit#2] opened 2015-04-04 09:57 UTC
Sorry to bother you again but I just can't seem to get this down. I have been getting this error:

XMLHttpRequest cannot load https://www.reddit.com/api/v1/access_token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8083' is therefore not allowed access. The response had HTTP status code 401.

This error appears after I call reddit.authFinish(response: authResponse) using the response from the authUrl. Thanks for the help in advance!

**Comment by stevenroose** [comment] 2015-04-07 01:57
It seems like this is bug in the Reddit API: https://github.com/reddit/reddit/issues/1225

I'll take a look at it and try to find a way around!

**Comment by ghost** [comment] 2015-04-07 02:36
@stevenroose I've tried! I ran into this awhile back in my own little reddit wrapper. Unfortunately there is no current way around this. Application only OAuth will not be supported until a CORS bug is worked out.

EDIT: **Application only OAuth in browsers. Works fine in Node/io.js

**Comment by stevenroose** [comment] 2015-04-07 20:38
@trevorsenior How about User Auth? It uses the same acces token endpoint, no?

**Comment by ghost** [comment] 2015-04-07 22:47
[Implicit OAuth](https://github.com/reddit/reddit/wiki/OAuth2#authorization-implicit-grant-flow) works fine (User Auth). It does not use the same endpoint. The difference between the two is that Implicit Based OAuth does not require a POST to the reddit servers like Application Only, but instead relies on redirection.

Basically you send the user to the authorization url, e.g.:

```
https://www.reddit.com/api/v1/authorize?client_id=CLIENT_ID&response_type=TYPE&
    state=RANDOM_STRING&redirect_uri=URI&scope=SCOPE_STRING
```

And then reddit will be redirected back to the application with an access token if they accepted.

**Comment by stevenroose** [comment] 2015-04-08 00:03
@trevorsenior OAuth2 specifies that after acquiring an authorization code at your redirect url, you have to use the token endpoint to acquire an access token. Does reddit differ from this?

I implemented in dart-reddit (for user auth)
- User provides client id and secret (but nothing happens)
- User requests auth url and forwards the end user to the url
- End user confirms and user acquires auth code at redirect url
- User provides auth code to lib
- Lib uses the code at access_token to request an access token

Does the Reddit API skip the final step?

**Comment by stevenroose** [comment] 2015-04-08 00:05
It's explained here, this is indeed the correct way to do it
https://github.com/reddit/reddit/wiki/OAuth2#token-retrieval-code-flow

And you do have to provide the auth code to `https://www.reddit.com/api/v1/access_token` (POST) so it will also be blocked by CORS.

It confuses me this problem exists, doesn't this make the complete Auth API useless?

**Comment by stevenroose** [comment] 2015-04-08 00:10
Only the [implicit grant flow](https://github.com/reddit/reddit/wiki/OAuth2#authorization-implicit-grant-flow) is missing from the lib.

**Comment by ghost** [comment] 2015-04-29 00:31
I forgot to comment back here -- this is fixed on reddit's end and should work fine in your library now.

I made sure that my client side [Implicit OAuth example](https://github.com/trevorsenior/snoocore-examples/blob/master/oauth-implicit.html) worked as intended before releasing a new version of my own little API wrapper.

**Comment by stevenroose** [comment] 2015-04-29 08:55
I was actually waiting for the Dart OAuth lib to support the implicit grant (https://github.com/dart-lang/tools/issues/301), but it doesn't seem like they will implement it soon. I'll probably implement the flow manually here, like you did.

**Comment by stevenroose** [comment] 2015-04-29 08:57
Made https://github.com/stevenroose/dart-reddit/issues/3 so this one can be closed.

**Closed as completed by stevenroose** 2015-04-29 08:57 UTC
